# Generated by Django 5.2.4 on 2025-07-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_userlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.CharField(max_length=20)),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobilenumber', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=256)),
                ('conformpassword', models.CharField(max_length=256)),
                ('status', models.CharField(default='active', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='userlogin',
        ),
    ]
