# Generated by Django 5.2.4 on 2025-07-28 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_userinfo_delete_userlogin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='conformpassword',
            new_name='confirmpassword',
        ),
    ]
