# Generated by Django 5.2.4 on 2025-07-28 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_rename_conformpassword_userinfo_confirmpassword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
