# Generated by Django 5.2.4 on 2025-07-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_delete_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobileno', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=256)),
                ('status', models.CharField(default='active', max_length=10)),
            ],
        ),
    ]
