# Generated by Django 5.2.4 on 2025-07-29 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_userlogin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlogin',
            old_name='mobileno',
            new_name='mobile',
        ),
    ]
