# Generated by Django 5.2.4 on 2025-07-29 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_rename_mobileno_userlogin_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlogin',
            old_name='usertype',
            new_name='userType',
        ),
    ]
