# Generated by Django 5.2.4 on 2025-07-31 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogin',
            name='status',
        ),
    ]
