# Generated by Django 5.2.4 on 2025-08-02 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_remove_userlogin_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogin',
            name='userType',
        ),
    ]
