# Generated by Django 5.2.4 on 2025-08-02 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_remove_userlogin_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='login',
        ),
        migrations.DeleteModel(
            name='UserLogin',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
