# Generated by Django 5.2.4 on 2025-08-02 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_userlogin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlogin',
            old_name='userType',
            new_name='usertype',
        ),
    ]
