# Generated by Django 5.2.4 on 2025-08-05 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractorapp', '0001_initial'),
        ('homeownerapp', '0001_initial'),
        ('mainapp', '0015_rename_usertype_userlogin_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_text', models.TextField()),
                ('progress_percent', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='progress_images/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='homeownerapp.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.userlogin')),
            ],
        ),
    ]
